apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xl2t69tgo-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xl2t69tgo-go 
  name: xl2t69tgo-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xl2t69tgo-go 
